apiVersion: v1
kind: Service
metadata:
  name: {{ include "klgn-bioit-wiki.fullname" . }}-serviceClusterIP
  labels:
    {{- include "klgn-bioit-wiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceClusterIP.type }}
  ports:
  - port: {{ .Values.serviceClusterIP.port }}
    targetPort: {{ .Values.serviceClusterIP.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "klgn-bioit-wiki.selectorLabels" . | nindent 4 }}
